apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conv-api-pvc
spec:
  resources:
    requests:
      storage: 500Mi
    limits:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
