apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-app-deployment #задаем имя деплоймента
spec:
  replicas: 1
  selector:
    matchLabels:
      components: frontend  
  template:  #задаем шаблон
    metadata:
      name: short-app
      labels:
        components: frontend
    spec:
      containers:
       - name: short-app
         image: antonlarichev/short-app:v1.4
         resources:
          limits:
            memory: "500Mi"
            cpu: "200m"
         ports:
          - containerPort: 80
 