---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-app-deployment #задаем имя деплоймента
spec:
  replicas: 1
  selector:
    matchLabels:
      components: frontend  
  template:  #задаем шаблон
    metadata:
      name: conv-app
      labels:
        components: frontend
    spec:
      containers:
       - name: conv-app
         image: antonlarichev/conv-app:1.2
         resources:
          limits:
            memory: "500Mi"
            cpu: "200m"
         ports:
          - containerPort: 80
         env:
            - name: VITE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: conv-app-configmap
                  key: VITE_DOMAIN
 