apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbitmq.name}}-secret
type: Opaque
stringData:
  AMQP_EXCHANGE: {{ .Values.rabbitmq.stringData.AMQP_EXCHANGE}}
  AMQP_USER: {{ .Values.rabbitmq.stringData.AMQP_USER}}
  AMQP_PASSWORD: {{ .Values.rabbitmq.stringData.AMQP_PASSWORD}}
  AMQP_HOSTNAME: {{ .Values.rabbitmq.stringData.AMQP_HOSTNAME}}
  AMQP_QUEUE: {{ .Values.rabbitmq.stringData.AMQP_QUEUE}}
